" .gvimrc

"FONT
":set guifont=*
":echo &guifont
"set guifont=Ricty_Diminished_Discord:h16:cSHIFTJIS:qDRAFT
"set guifont=HackGen_Console:h12:cSHIFTJIS:qDRAFT
"set guifont=BIZ_UDゴシック:h12:cSHIFTJIS:qDRAFT
set guifont=HackGen_Console_NF:h14:cSHIFTJIS:qDRAFT

