" .vimrc
"
" vim-plug
let data_dir = has('nvim') ? stdpath('data') . '/site' : has('win32') ? '~/vimfiles' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)')) | PlugInstall --sync | source $MYVIMRC | endif

" Initialize plugin system
call plug#begin()
Plug 'itchyny/lightline.vim'
Plug 'glidenote/memolist.vim'
Plug 'vim-jp/vimdoc-ja'
Plug 'vim-scripts/vim-auto-save'
Plug 'mattn/vim-sonictemplate'
Plug 'yasukotelin/shirotelin'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'delphinus/vim-auto-cursorline'
call plug#end()

"
set nocompatible
set nowritebackup
set nobackup
set virtualedit=block
set backspace=indent,eol,start
set ambiwidth=double
set wildmenu

set ignorecase
set smartcase
set wrapscan
set incsearch
set hlsearch

set noerrorbells
"set shellslash
set showmatch matchtime=1
set cinoptions+=:0
set cmdheight=2
set laststatus=2
set showcmd
set display=lastline
set list
set listchars=tab:^\ ,trail:~
set history=10000
hi Comment ctermfg=3
set shiftwidth=0
set softtabstop=-1
set tabstop=2
set expandtab
set guioptions-=T
set guioptions+=a
" set guioptions-=m
set guioptions+=R
set showmatch
set smartindent
set noswapfile
" set nofoldenable
set title
set number
set clipboard=unnamed,autoselect
nnoremap <Esc><Esc> :nohlsearch<CR><ESC>
syntax on
set nrformats=
set whichwrap=b,s,h,l<,>,[,],~
set mouse=a
set visualbell

set background=dark
"set background=light
"colorscheme desert
"colorscheme toast
colorscheme shirotelin
set termguicolors

set rop=type:directx

set scrolloff=5
set sidescrolloff=8
set sidescroll=1
set cursorline
"set guifont=HackGen_Console:h14:cSHIFTJIS:qDRAFT

" vim-auto-save
let g:auto_save_events = ["InsertLeave", "TextChanged"]

"let g:lightline = {
"      \ 'colorscheme': 'wombat'
"      \ }

"let g:lightline = {
"      \ 'colorscheme': 'powerline',
"      \ 'active': {
"      \   'left': [ [ 'mode', 'paste' ],
"      \             [  'readonly', 'filename', 'modified' ] ]
"      \ },
"      \ }

"\ 'colorscheme': 'wombat',
let g:lightline = {
        \ 'colorscheme': 'shirotelin',
        \ 'mode_map': {'c': 'NORMAL'},
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ], [ 'fugitive', 'filename' ] ]
        \ },
        \ 'component_function': {
        \   'modified': 'LightlineModified',
        \   'readonly': 'LightlineReadonly',
        \   'fugitive': 'LightlineFugitive',
        \   'filename': 'LightlineFilename',
        \   'fileformat': 'LightlineFileformat',
        \   'filetype': 'LightlineFiletype',
        \   'fileencoding': 'LightlineFileencoding',
        \   'mode': 'LightlineMode'
        \ }
        \ }

function! LightlineModified()
  return &ft =~ 'help\|vimfiler\|gundo' ? '' : &modified ? '+' : &modifiable ? '' : '-'
endfunction

function! LightlineReadonly()
  return &ft !~? 'help\|vimfiler\|gundo' && &readonly ? 'x' : ''
endfunction

function! LightlineFilename()
  return ('' != LightlineReadonly() ? LightlineReadonly() . ' ' : '') .
        \ (&ft == 'vimfiler' ? vimfiler#get_status_string() :
        \  &ft == 'unite' ? unite#get_status_string() :
        \  &ft == 'vimshell' ? vimshell#get_status_string() :
        \ '' != expand('%:t') ? expand('%:t') : '[No Name]') .
        \ ('' != LightlineModified() ? ' ' . LightlineModified() : '')
endfunction

function! LightlineFugitive()
  if &ft !~? 'vimfiler\|gundo' && exists('*fugitive#head')
    return fugitive#head()
  else
    return ''
  endif
endfunction

function! LightlineFileformat()
  return winwidth(0) > 70 ? &fileformat : ''
endfunction

function! LightlineFiletype()
  return winwidth(0) > 70 ? (&filetype !=# '' ? &filetype : 'no ft') : ''
endfunction

function! LightlineFileencoding()
  return winwidth(0) > 70 ? (&fenc !=# '' ? &fenc : &enc) : ''
endfunction

function! LightlineMode()
  return winwidth(0) > 60 ? lightline#mode() : ''
endfunction

let mapleader="\<Space>"
let g:memolist_path="~/OneDrive/vim-memolist"
let g:memolist_memo_suffix = "md"
let g:memolist_template_dir_path="~/OneDrive/vim-memolist"
let g:auto_save=1
map <Leader>mn  :MemoNew<CR>
map <Leader>ml  :MemoList<CR>
map <Leader>mg  :MemoGrep<CR>


" Vim-lspでtextlintを使う設定
" プラグインvim-lsp, vim-lsp-settings, efm-langserverのビルドにgo, textlintの実行にnode.js
"
" go,node.jsともにインストーラーを使わずにzip形式のバイナリを利用する
"
" go言語とnode.jsのインストールはzip形式展開して置く。それぞれ次の位置にくるように
" %USERPROFILE%\App\go1.20.1.windows-amd64\go\bin\go.exe
" %USERPROFILE%\App\node-v18.15.0-win-x64\node.exe
"
" PATHを設定
" path %path%;%USERPROFILE%\App\go1.20.1.windows-amd64\go;%USERPROFILE%\App\node-v18.15.0-win-x64
"
" 環境変数を設定
" set GOPATH=%USERPROFILE%\App\go1.20.1.windows-amd64\go
" set NODE_PATH=%USERPROFILE%\App\node-v18.15.0-win-x64\node_modules
"
" textlintの設定ファイルの位置はここ(textlint --config textlint-config-<name>)
" %USERPROFILE%\.textlintrc
"
" 参考
" https://github.com/prabirshrestha/vim-lsp
" https://github.com/mattn/vim-lsp-settings
" https://github.com/mattn/efm-langserver
" https://zenn.dev/skanehira/articles/2020-11-16-vim-writing-articles
"
let g:lsp_diagnostics_signs_enabled = 1
let g:lsp_diagnostics_signs_error = {"text": "💩"}
"let g:lsp_diagnostics_signs_error = {"text": "❌"}
let g:lsp_diagnostics_signs_warning = {"text": "👻"}
"let g:lsp_diagnostics_signs_warning = {"text": "⚠️"}
let g:lsp_diagnostics_signs_information = {"text": "❗"}
let g:lsp_diagnostics_signs_hint = {"text": "❓"}

let g:lsp_document_code_action_signs_enabled = 1
let g:lsp_document_code_action_signs_hint = {"text": "❓"}
if !has('nvim')
  let g:lsp_diagnostics_float_cursor = 1
endif

"ログ採取
"let g:lsp_log_verbose = 1
"let g:lsp_log_file = expand('~/vim-lsp.log')

"vim-lsp-settingsのサーバインストール先
let g:lsp_settings_servers_dir = expand('~/vimfiles/vim-lsp-servers')
"デフォルトvim-lsp-settingsで導入されるefm-langerverの位置はここ(let g:lsp_settings_servers_dir=<path> )
" %USERPROFILE%\AppData\Local\vim-lsp-settings\servers\efm-langserver\efm-langserver.exe

"vim-lsp-settingsの設定
let g:lsp_settings = {
      \ 'efm-langserver': {
      \   'args': ['-c', expand('~/vimfiles/vim-lsp-servers/efm-langserver-config.yaml')],
      \   'disabled': 0,
      \   'allowlist': ['markdown'],
      \  }
      \ }
" デフォルトefm-langserverの設定ファイルの位置はここ(efm-langserver -c <config.yaml>)
" %USERPROFILE%\AppData\Roaming\efm-langserver\config.yaml
"
function! s:on_lsp_buffer_enabled() abort
  setlocal completeopt=menu
  setlocal omnifunc=lsp#complete
  setlocal signcolumn=yes
endfunction

augroup lsp_install
  au!
  au User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
