" .vimrc

"
" vim-plug
let data_dir = has('nvim') ? stdpath('data') . '/site' : has('win32') ? '~/vimfiles' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)')) | PlugInstall --sync | source $MYVIMRC | endif

" Initialize plugin system
call plug#begin()
Plug 'itchyny/lightline.vim'
Plug 'glidenote/memolist.vim'
Plug 'vim-jp/vimdoc-ja'
Plug 'vim-scripts/vim-auto-save'
"Plug 'mattn/vim-sonictemplate'
"
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'

Plug 'delphinus/vim-auto-cursorline'
Plug 'rhysd/vim-healthcheck'

Plug 'yasukotelin/shirotelin'
Plug 'preservim/vim-colors-pencil'
Plug 'yami-beta/lightline-pencil.vim'

""Plug 'neoclide/coc.nvim', {'branch': 'release'}

Plug 'mhinz/vim-startify'
Plug 'EdenEast/nightfox.nvim'

"https://github.com/tpope/vim-surround
Plug 'tpope/vim-surround'
"https://github.com/jiangmiao/auto-pairs
Plug 'jiangmiao/auto-pairs'

call plug#end()

"
set lines=32
set columns=120

set nocompatible
set nowritebackup
set nobackup
set virtualedit=block
set backspace=indent,eol,start
set ambiwidth=double
set wildmenu

"内部コード
set encoding=utf-8
"読み込み時コード( 指定して再読み込みは :e ++enc=utf-8)
set fileencodings=utf-8,sjis,iso-20220jp,euc-jp
set fileformats=unix,dos,mac

set ignorecase
set smartcase
set wrapscan
set incsearch
set hlsearch

set noerrorbells
"set shellslash
set showmatch matchtime=1
set cinoptions+=:0
set cmdheight=2
set laststatus=2
set signcolumn=yes

set showcmd
set display=lastline
set list
set listchars=tab:^\ ,trail:~

set history=10000
hi Comment ctermfg=3
set shiftwidth=0
set softtabstop=-1
set tabstop=2
set expandtab
set guioptions-=T
set guioptions+=a
" set guioptions-=m
set guioptions+=R
set showmatch
set smartindent
set noswapfile
" set nofoldenable
set title
set number
set clipboard=unnamed,autoselect

nnoremap <Esc><Esc> :nohlsearch<CR><ESC>
nnoremap k gk
nnoremap j gj
nnoremap gk k
nnoremap gj j
nnoremap J gJ
nnoremap gJ J

syntax on
set nrformats=
set whichwrap=b,s,h,l<,>,[,],~
set mouse=a
set visualbell

set background=dark
"set background=light

"colorscheme desert
"colorscheme toast
"colorscheme shirotelin
"colorscheme pencil
colorscheme dayfox
"colorscheme duskfox
set termguicolors

set rop=type:directx

set scrolloff=5
set sidescrolloff=8
set sidescroll=1
set cursorline
"set guifont=HackGen_Console:h14:cSHIFTJIS:qDRAFT

set confirm

" vim-auto-save
let g:auto_save_events = ["InsertLeave", "TextChanged"]

" Lightline
let g:lightline = {
        \ 'colorscheme': 'dayfox',
        \ 'mode_map': {'c': 'NORMAL'},
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ], [ 'fugitive', 'filename' ] ]
        \ },
        \ 'component_function': {
        \   'modified': 'LightlineModified',
        \   'readonly': 'LightlineReadonly',
        \   'fugitive': 'LightlineFugitive',
        \   'filename': 'LightlineFilename',
        \   'fileformat': 'LightlineFileformat',
        \   'filetype': 'LightlineFiletype',
        \   'fileencoding': 'LightlineFileencoding',
        \   'mode': 'LightlineMode'
        \ }
        \ }

function! LightlineModified()
  return &ft =~ 'help\|vimfiler\|gundo' ? '' : &modified ? '+' : &modifiable ? '' : '-'
endfunction

function! LightlineReadonly()
  return &ft !~? 'help\|vimfiler\|gundo' && &readonly ? 'x' : ''
endfunction

function! LightlineFilename()
  return ('' != LightlineReadonly() ? LightlineReadonly() . ' ' : '') .
        \ (&ft == 'vimfiler' ? vimfiler#get_status_string() :
        \  &ft == 'unite' ? unite#get_status_string() :
        \  &ft == 'vimshell' ? vimshell#get_status_string() :
        \ '' != expand('%:t') ? expand('%:t') : '[No Name]') .
        \ ('' != LightlineModified() ? ' ' . LightlineModified() : '')
endfunction

function! LightlineFugitive()
  if &ft !~? 'vimfiler\|gundo' && exists('*fugitive#head')
    return fugitive#head()
  else
    return ''
  endif
endfunction

function! LightlineFileformat()
  return winwidth(0) > 70 ? &fileformat : ''
endfunction

function! LightlineFiletype()
  return winwidth(0) > 70 ? (&filetype !=# '' ? &filetype : 'no ft') : ''
endfunction

function! LightlineFileencoding()
  return winwidth(0) > 70 ? (&fenc !=# '' ? &fenc : &enc) : ''
endfunction

function! LightlineMode()
  return winwidth(0) > 60 ? lightline#mode() : ''
endfunction

let mapleader="\<Space>"
let g:memolist_path="$USERPROFILE/OneDrive/vim-memolist"
let g:memolist_memo_suffix = "md"
let g:memolist_template_dir_path="~/OneDrive/vim-memolist"
let g:auto_save=1
map <Leader>mn  :MemoNew<CR>
map <Leader>ml  :MemoList<CR>
map <Leader>mg  :MemoGrep<CR>

"
" Vim-lspでtextlintを使う設定
"
" 参考
"   https://github.com/prabirshrestha/vim-lsp
"   https://github.com/mattn/vim-lsp-settings
"   https://github.com/mattn/efm-langserver
"   https://zenn.dev/skanehira/articles/2020-11-16-vim-writing-articles
"
" 必要なもの
" Vimプラグインvim-lsp, vim-lsp-settings
" efm-langserverのビルドにgo,
" textlintの実行にnodejs
" go,nodejsともにインストーラーを使わずにzip形式のバイナリを使う前提
" go言語とnode.jsのインストールはzip形式展開して適当なフォルダに置く。
" ちなみにインストーラーでインストールするとインストール先は
"   C:\Program Files\go
"   C:\Program Files\nodejs
"
" PATHにgo/bin(インストール先の下のbin)とnodejs(=インストール先)と
" %APPDATA\npm(=C:%USERPROFILE%\AppData\Roaming\npm)を追加する。
" ちなみに%APPDATA\npmはnodejs/node_modules/npm/npmrcに書いてある
" prefix=${APPDATA}\npmのこと
"
" それ以外の環境変数は特に設定しなくてもいいようだ
" 設定するとしたら
"   set GOPATH=goのインストール先
"   set NODE_PATH=nodejs\node_modules
"
" textlintの設定ファイル.txtlintrcの位置
"   %USERPROFILE%\.textlintrc
"

let g:lsp_diagnostics_signs_enabled = 1
let g:lsp_diagnostics_signs_error = {"text": "e>"}
let g:lsp_diagnostics_signs_warning = {"text": "w>"}
let g:lsp_diagnostics_signs_information = {"text": "i>"}
let g:lsp_diagnostics_signs_hint = {"text": "h>"}

let g:lsp_document_code_action_signs_enabled = 1
let g:lsp_document_code_action_signs_hint = {"text": "h>"}
if !has('nvim')
  let g:lsp_diagnostics_float_cursor = 1
endif

"ログ採取
"let g:lsp_log_verbose = 1
"let g:lsp_log_file = expand('~/vim-lsp.log')

"vim-lsp-settingsのサーバインストール先
"デフォルトvim-lsp-settingsで導入されるefm-langerverの位置はここ
" %USERPROFILE%\AppData\Local\vim-lsp-settings\servers\efm-langserver\efm-langserver.exe
"インストール先を変えるならlet g:lsp_settings_servers_dir=<path> に設定する
"let g:lsp_settings_servers_dir = expand('~/vimfiles/vim-lsp-servers')

" vimrcのvim-lsp-settingsの設定
let g:lsp_settings = {
      \ 'efm-langserver': {
      \   'disabled': 0,
      \   'allowlist': ['markdown'],
      \  }
      \ }

" デフォルトefm-langserverの設定ファイルconfigの位置はここ
" %USERPROFILE%\AppData\Roaming\efm-langserver\config.yaml
"(efm-langserver -c <config.yaml>)
"
function! s:on_lsp_buffer_enabled() abort
  setlocal completeopt=menu
  setlocal omnifunc=lsp#complete
  setlocal signcolumn=yes

  nmap <buffer> [g <plug>(lsp-previous-diagnostic)
  nmap <buffer> ]g <plug>(lsp-next-diagnostic)
endfunction

augroup lsp_install
  au!
  au User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

" Lsp Hignlight color:Pencil
" Normal         xxx ctermfg=8 ctermbg=15 guifg=#424242 guibg=#F1F1F1
" Error          xxx term=reverse cterm=bold ctermfg=231 ctermbg=1 gui=bold guifg=#FFFFFF guibg=#C30771
" Todo           xxx term=standout cterm=bold ctermfg=231 ctermbg=9 gui=bold guifg=#FFFFFF guibg=#fb007a
" SpellBad       xxx term=reverse cterm=undercurl ctermfg=1 gui=undercurl guifg=#C30771 guisp=#C30771
" SpellRare      xxx term=reverse cterm=undercurl ctermfg=9 gui=undercurl guifg=#fb007a guisp=#fb007a
highlight LspErrorHighlight term=reverse cterm=undercurl ctermfg=8 ctermbg=15 gui=undercurl guifg=#424242 guibg=#F1F1F1 guisp=#C30771
highlight LspWaningHighlight term=reverse cterm=undercurl ctermfg=8 ctermbg=15 gui=undercurl guifg=#5FD7A7 guisp=#5FD7A7 guisp=#fb007a
highlight link LspErrorText Normal
highlight link LspWarningText Normal

" BASH
function! GitBash()
  let l:option = {
        \ 'term_name': 'Git',
        \ 'term_finish': 'close',
        \ 'curwin': v:false,
        \ 'cwd': $USERPROFILE,
        \ }

  let l:terminal_buf=term_start('C:/Program Files/Git/bin/bash.exe', l:option)
  call term_sendkeys(l:terminal_buf, "export LANG=\"ja_JP.utf-8\"\<CR>")
  call term_sendkeys(l:terminal_buf, "clear\<CR>")

endfunction
nnoremap <Leader>g :<C-u>call GitBash()<CR>

" https://note.com/yasukotelin/n/na87dc604e042
" 補完表示時のEnterで改行をしない
inoremap <expr><CR>  pumvisible() ? "<C-y>" : "<CR>"

set completeopt=menuone,noinsert
inoremap <expr><C-n> pumvisible() ? "<Down>" : "<C-n>"
inoremap <expr><C-p> pumvisible() ? "<Up>" : "<C-p>"

